#!/usr/bin/env bash

# Description: Transfers a file from a client to a server using scp.
# Usage: transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# Arguments:
#    PATH_TO_FILE: The path to the file to be transferred.
#    IP: The IP address of the server to transfer the file to.
#    USERNAME: The username for the scp connection.
#    PATH_TO_SSH_KEY: The path to the SSH private key that scp uses.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
