#!/usr/bin/env bash
# Display numbers from 1 to 100 with FizzBuzz logic

for num in {1..100}; do
  # Check for FizzBuzz
  if (( num % 3 == 0 && num % 5 == 0 )); then
    echo "FizzBuzz"
  # Check for Fizz
  elif (( num % 3 == 0 )); then
    echo "Fizz"
  # Check for Buzz
  elif (( num % 5 == 0 )); then
    echo "Buzz"
  # Otherwise, print the number
  else
    echo "$num"
  fi
done
