#!/usr/bin/env bash
# This script displays "Best School" 10 times, saying "Hi!" after the 9th iteration

i=0
while [ $i -lt 11 ]
do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    (( i+=1 ))
done
