#!/usr/bin/env bash
# Displays numbers from 1 to 20 with superstitious notes

i=1
while [ $i -lt 21 ]
do
    case $i in

        4)
	    echo $i
	    echo "bad luck from China"
	    ;;

	9)
	    echo $i
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo $i
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $i
	    ;;
    esac

    ((i+=1))
done
