#!/usr/bin/env bash
# Display hours from 0 to 12 and minutes from 1 to 59

HOURS=0
while [ $HOURS -lt 13 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 60 ]
    do
        echo $MINUTES
	let MINUTES+=1
    done
    let HOURS+=1
done
